//
// Created by alexium on 19.03.2022.
//

#ifndef SGM_SRC_ENGINE_RENDERS_2D_SDL_EXPORT_TEXTURE_FORMATS_H_
#define SGM_SRC_ENGINE_RENDERS_2D_SDL_EXPORT_TEXTURE_FORMATS_H_

#define IMG_EXT "png"
#define IMG_SCL_X 80
#define IMG_SCL_Y 80

#endif //SGM_SRC_ENGINE_RENDERS_2D_SDL_EXPORT_TEXTURE_FORMATS_H_
